server:
  servlet:
    context-path: /wms-admin
  port: 8081

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳,2天
  expiresSecond: 172800

spring:
  profiles:
    active: dev

logging:
  config: classpath:logback-boot.xml
