# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gankun_wms_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: hikari_jdbc_conn_pool
      auto-commit: true
